version: '3.8'

services:
  app:
    build:
      context: .
    command: bash start.sh
    ports:
      - "8080:8080" #porta do container cmo bind da máquina real, para enviarmos requisições para api o container entender isso.
      - "5005:5005" # porta para debug
    environment:
      GRADLE_USER_HOME: /box # container para cache das dependências
    volumes:
      - .:/reactive-flashcards
      - box:/box # volume dos arquivos e das dependências do projeto
    depends_on:
      - db
  db:
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: reactive-flashcards
      MONGO_INITDB_ROOT_PASSWORD: reactive-flashcards
      MONGO_INITDB_DATABASE: reactive-flashcards
    ports:
      - "27017:27017"
  box:
    image: busybox
    volumes:
      - /box
volumes:
  db:
  box: